[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev:vite"
  targetPort = 3000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 